{
 "title": "Coiled Cluster Metrics — Basic",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(node_cpu_seconds_total, env)"
    }
   },
   {
    "name": "account",
    "label": "Account",
    "query": {
     "query": "label_values(node_cpu_seconds_total{env=~\"$env\"}, account)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "node_cpu_seconds_total{account=\"$account\",env=~\"$env\"}"
    }
   },
   {
    "name": "cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(node_cpu_seconds_total{account=\"$account\",env=~\"$env\",cluster=\"$cluster\"}, cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Workers Connected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\n    # any workers connected\n    count(\n        sum(dask_scheduler_workers{cluster_id=\"$cluster_id\",state!=\"connected\"})\n        # only trust metric when scheduler is running\n        and on () sum(rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}[$__rate_interval])) > 0\n    \n    \n    )[12h:1s]\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\n    (dask_scheduler_tasks{cluster_id=\"$cluster_id\",state=\"processing\"} > bool 0)[12h:1s]\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Workers \"Idle\"",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\n(\n\n# all instances are idle\n(\n# idle workers / connected workers\ndask_scheduler_workers{cluster_id=\"$cluster_id\",state=\"idle\"}\n/ on () sum(dask_scheduler_workers{cluster_id=\"$cluster_id\",state!=\"connected\"})\n# only trust metric when scheduler is running\nand on () sum(rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}[$__rate_interval])) > 0\n) == 1\n\n)[12h:1s]\n) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "* Idle CPU (<10% avg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\n(\n    count(\n        # average CPU over entire cluster < 20%\n        avg(sum by(instance,cpu) (irate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"worker\", mode!=\"idle\"}[$__rate_interval]))) < .1\n        # when tasks were processing\n        and on () dask_scheduler_tasks{cluster_id=\"$cluster_id\",state=\"processing\"} > 0\n    )\n)[12h:1s]\n) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Pressure (20% of workers >60%)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\n(\n# for at least 20% of workers\n(\n    # number of instances with\n    count(\n        # 60% or higher mem util (i.e., less than 40% available)\n        (node_memory_MemAvailable_bytes{cluster_id=\"$cluster_id\", spec=\"worker\"} / node_memory_MemTotal_bytes{cluster_id=\"$cluster_id\", spec=\"worker\"}) < .4\n    )\n) / count(count by (instance) (sum_over_time(dask_worker_threads{cluster_id=\"$cluster_id\"}[2m]) > 0)) > bool .2\n# when tasks were processing\n# and on () dask_scheduler_tasks{cluster_id=\"$cluster_id\",state=\"processing\"} > 0\n\n)[12h:1s]\n) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance 80% Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(    \n    count(\n        # for at least 1 worker\n        (\n            # number of instances with\n            count(\n                # 80% or higher mem util (i.e., less than 20% available)\n                (node_memory_MemAvailable_bytes{cluster_id=\"$cluster_id\", spec=\"worker\"} / node_memory_MemTotal_bytes{cluster_id=\"$cluster_id\", spec=\"worker\"}) < .2\n            )\n        ) > 1\n    )[12h:1s]\n) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "* Non-Trivial Write",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\n(\n# for at least 20% of workers\n(\n    count(\n        # write rate is at least 20MiB/s\n        rate(node_disk_written_bytes_total{cluster_id=\"$cluster_id\", spec=\"worker\"}[$__rate_interval])\n        and rate(node_disk_written_bytes_total{cluster_id=\"$cluster_id\", spec=\"worker\"}[$__rate_interval]) > 20000000\n        # while there are tasks processing\n        and on () dask_scheduler_tasks{cluster_id=\"$cluster_id\",state=\"processing\"} > 0\n    )\n    / count(count by (instance) (sum_over_time(dask_worker_threads{cluster_id=\"$cluster_id\"}[2m]) > 0))\n) > bool .2\n)[12h:1s]\n) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "* Non-Trivial Recv (>10MiB/s Avg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\n(\n    # at least one instance with recv rate over 10MiB/s\n    count(\n        avg (\n            rate(node_network_receive_bytes_total{cluster_id=\"$cluster_id\", spec=\"worker\"}[$__rate_interval])\n        ) > 10000000\n    )\n    # while there are tasks processing\n    and on () dask_scheduler_tasks{cluster_id=\"$cluster_id\",state=\"processing\"} > 0\n\n)[12h:1s]\n) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Erred Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "dask_scheduler_tasks{cluster_id=\"$cluster_id\",state=\"erred\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Event Loop Blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time(\n(\n\n  # any workers aren't reporting dask metrics\n  (\n    count(\n      sum by (instance)(rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\",spec=\"worker\"}[$__rate_interval]) > 0)\n    )\n    - count(dask_worker_threads{cluster_id=\"$cluster_id\"})\n  ) > 0\n  # only trust metric when scheduler is running\n  and on () sum(rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}[$__rate_interval])) > 0\n\n)[12h:1s]\n) ",
     "legendFormat": "cores"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 3 },
   "options": {
    "content": "* Duration only includes times\n when tasks on scheduler were\n in <u>processing</u> state"
   }
  },
  {
   "title": "Task Prefix Compute Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "rate(dask_scheduler_tasks_compute_seconds_total{cluster_id=\"$cluster_id\"}[$__rate_interval])",
     "legendFormat": "{{task_prefix_name}}"
    },
    {
     "expr": "sum(rate(dask_scheduler_tasks_compute_seconds_total{cluster_id=\"$cluster_id\"}[$__rate_interval]) > 0)",
     "legendFormat": "total time"
    },
    {
     "expr": "sum(dask_worker_threads{cluster_id=\"$cluster_id\"})",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "Task Prefix Compute Time",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(dask_scheduler_tasks_compute_seconds_total{cluster_id=\"$cluster_id\"}[6h])",
     "legendFormat": "{{task_prefix_name}}"
    }
   ]
  },
  { "title": "Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Average Worker CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(mode) (irate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"worker\", mode!=\"idle\"}[$__rate_interval])) * 100",
     "legendFormat": "{{mode}}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expr": "quantile(0.8, \navg by(coiled_instance) (100-irate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"worker\", mode=\"idle\"}[$__rate_interval])*100)\n)",
     "legendFormat": "80pct",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expr": "max(\navg by(coiled_instance) (100-irate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"worker\", mode=\"idle\"}[$__rate_interval])*100)\n)",
     "legendFormat": "Max",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Worker Net Sent/Recv Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum((rate(node_network_transmit_bytes_total{cluster_id=\"$cluster_id\", spec=\"worker\"}[$__rate_interval])))",
     "legendFormat": "Sent",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expr": "sum((rate(node_network_receive_bytes_total{cluster_id=\"$cluster_id\", spec=\"worker\"}[$__rate_interval])))",
     "legendFormat": "Recv",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expr": "max((rate(node_network_receive_bytes_total{cluster_id=\"$cluster_id\", spec=\"worker\"}[$__rate_interval])))",
     "legendFormat": "Max per instance recv",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Cluster Worker Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (dask_worker_memory_bytes{cluster_id=\"$cluster_id\", type=\"managed\"})\n# only trust metric when scheduler is running\nand on () sum(rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}[$__rate_interval])) > 0",
     "legendFormat": "managed"
    },
    {
     "expr": "sum (dask_worker_memory_bytes{cluster_id=\"$cluster_id\", type=\"unmanaged\"})\n# only trust metric when scheduler is running\nand on () sum(rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}[$__rate_interval])) > 0",
     "legendFormat": "unmanaged"
    },
    {
     "expr": "sum (dask_worker_memory_bytes{cluster_id=\"$cluster_id\", type=\"spilled\"})\n# only trust metric when scheduler is running\nand on () sum(rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}[$__rate_interval])) > 0",
     "legendFormat": "spilled"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster_id=\"$cluster_id\", spec=\"worker\"})\n# only trust metric when scheduler is running\nand on () sum(rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}[$__rate_interval])) > 0",
     "legendFormat": "cluster total memory"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster_id=\"$cluster_id\", spec=\"worker\"} - node_memory_MemAvailable_bytes{cluster_id=\"$cluster_id\", spec=\"worker\"})\n# only trust metric when scheduler is running\nand on () sum(rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}[$__rate_interval])) > 0",
     "legendFormat": "cluster total occupied"
    },
    {
     "expr": "sum (dask_worker_memory_bytes{cluster_id=\"$cluster_id\", type=~\"unmanaged|managed\"})\n# only trust metric when scheduler is running\nand on () sum(rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}[$__rate_interval])) > 0",
     "legendFormat": "dask total memory"
    }
   ]
  },
  {
   "title": "Worker Disk Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (rate(node_disk_read_bytes_total{cluster_id=\"$cluster_id\", spec=\"worker\"}[$__rate_interval]))",
     "legendFormat": "Read",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expr": "sum (rate(node_disk_written_bytes_total{cluster_id=\"$cluster_id\", spec=\"worker\"}[$__rate_interval]))",
     "legendFormat": "Write",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expr": "max (rate(node_disk_read_bytes_total{cluster_id=\"$cluster_id\", spec=\"worker\"}[$__rate_interval]) + rate(node_disk_written_bytes_total{cluster_id=\"$cluster_id\", spec=\"worker\"}[$__rate_interval]))",
     "legendFormat": "Max per instance read+write",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Cluster Occupancy",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(sum by (instance, cpu)(rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\",spec=\"worker\"}[$__rate_interval]) > 0))",
     "legendFormat": "cores"
    },
    {
     "expr": "sum by(state) (dask_worker_tasks{cluster_id=\"$cluster_id\",state=\"executing\"})\n# only trust metric when scheduler is running\nand on () sum(rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}[$__rate_interval])) > 0",
     "legendFormat": "executing",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expr": "sum(dask_worker_threads{cluster_id=\"$cluster_id\"})\n# only trust metric when scheduler is running\nand on () sum(rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}[$__rate_interval])) > 0",
     "legendFormat": "threads (for responding workers)"
    }
   ]
  },
  {
   "title": "Task States (Scheduler)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(state) (dask_scheduler_tasks{cluster_id=\"$cluster_id\"}) != 0\n# only trust metric when scheduler is running\nand on () sum(rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}[$__rate_interval])) > 0",
     "legendFormat": "__auto",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Worker Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "dask_scheduler_workers{cluster_id=\"$cluster_id\",state!=\"connected\"}\n# only trust metric when scheduler is running\nand on () sum(rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}[$__rate_interval])) > 0",
     "legendFormat": "{{state}}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expr": "(dask_scheduler_workers{cluster_id=\"$cluster_id\",state=\"connected\"} - on () sum(dask_scheduler_workers{cluster_id=\"$cluster_id\",state!=\"connected\"}))\n# only trust metric when scheduler is running\nand on () sum(rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}[$__rate_interval])) > 0",
     "legendFormat": "neither idle nor saturated",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Task States (Workers)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(state) (dask_worker_tasks{cluster_id=\"$cluster_id\",state!=\"executing\"}) != 0\n# only trust metric when scheduler is running\nand on () sum(rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}[$__rate_interval])) > 0",
     "legendFormat": "__auto",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Scheduler CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(mode) (rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"scheduler\", mode!=\"idle\"}[$__rate_interval])) * 100",
     "legendFormat": "__auto",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expr": "max(sum by (cpu) (rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"scheduler\", mode!=\"idle\"}[$__rate_interval]))) * 100",
     "legendFormat": "max single core util",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Scheduler Bytes Sent/Recv Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "$ClusterName", "InstanceSpecName": "scheduler", "interface": "ens5" },
     "expr": "sum(rate(node_network_receive_bytes_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}[$__rate_interval]))",
     "legendFormat": "Recv",
     "metricName": "net_bytes_sent",
     "namespace": "Coiled/Clusters",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ClusterName": "$ClusterName", "InstanceSpecName": "scheduler", "interface": "ens5" },
     "expr": "sum(rate(node_network_transmit_bytes_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}[$__rate_interval]))",
     "legendFormat": "Sent",
     "metricName": "net_bytes_sent",
     "namespace": "Coiled/Clusters",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Scheduler Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "\n  (\n    node_memory_MemTotal_bytes{cluster_id=\"$cluster_id\", spec=\"scheduler\"}\n    - node_memory_MemAvailable_bytes{cluster_id=\"$cluster_id\", spec=\"scheduler\"}\n  ) / node_memory_MemTotal_bytes{cluster_id=\"$cluster_id\", spec=\"scheduler\"}\n# only trust metric when scheduler is running\nand on () sum(rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}[$__rate_interval])) > 0",
     "legendFormat": "Non-Free Memory"
    }
   ]
  },
  {
   "title": "Scheduler Net Sent/Recv Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}\n# only trust metric when scheduler is running\nand on () sum(rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}[$__rate_interval])) > 0",
     "legendFormat": "Sent",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expr": "-(node_network_receive_bytes_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"} - min_over_time(node_network_receive_bytes_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}[12h]))\n# only trust metric when scheduler is running\nand on () sum(rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}[$__rate_interval])) > 0",
     "legendFormat": "Recv (after docker pull)",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Worker — Disk/Network Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Worker Disk Used (Attached Disk)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{cluster_id=\"$cluster_id\", mountpoint=\"/\", spec=\"worker\"} - node_filesystem_free_bytes{cluster_id=\"$cluster_id\", mountpoint=\"/\", spec=\"worker\"})/node_filesystem_size_bytes{cluster_id=\"$cluster_id\", mountpoint=\"/\", spec=\"worker\"}",
     "legendFormat": "{{coiled_instance}}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Worker Scratch Used (NVMe)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{cluster_id=\"$cluster_id\", mountpoint=\"/scratch\", spec=\"worker\"} - node_filesystem_free_bytes{cluster_id=\"$cluster_id\", mountpoint=\"/scratch\", spec=\"worker\"})/node_filesystem_size_bytes{cluster_id=\"$cluster_id\", mountpoint=\"/scratch\", spec=\"worker\"}",
     "legendFormat": "{{coiled_instance}}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Worker Net Sent/Recv Max Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max (rate(node_network_transmit_bytes_total{cluster_id=\"$cluster_id\", spec=\"worker\"}[$__rate_interval]))",
     "legendFormat": "Sent",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expr": "max (rate(node_network_receive_bytes_total{cluster_id=\"$cluster_id\", spec=\"worker\"}[$__rate_interval]))",
     "legendFormat": "Recv",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Worker Net Sent/Recv Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_network_transmit_bytes_total{cluster_id=\"$cluster_id\", spec=\"worker\"})\n# only trust metric when scheduler is running\nand on () sum(rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}[$__rate_interval])) > 0",
     "legendFormat": "Sent",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expr": "sum(node_network_receive_bytes_total{cluster_id=\"$cluster_id\", spec=\"worker\"})\n# only trust metric when scheduler is running\nand on () sum(rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"scheduler\"}[$__rate_interval])) > 0",
     "legendFormat": "Recv",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Worker — Memory/CPU Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Aggregate Worker CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(mode) (rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"worker\", mode!=\"idle\"}[$__rate_interval])) * 100",
     "legendFormat": "{{mode}}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expr": "count(sum by (instance, cpu) (node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"worker\"})) * 100",
     "legendFormat": "cores"
    },
    {
     "expr": "count(sum by (instance) (node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"worker\"})) * 100",
     "legendFormat": "single-core capacity"
    }
   ]
  },
  {
   "title": "Worker CPU Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(mode)\n(rate(node_cpu_seconds_total{cluster_id=\"$cluster_id\",spec=\"worker\", mode!=\"idle\"}[$__rate_interval]))",
     "legendFormat": "{{mode}}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expr": "max(\n (1-irate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"worker\", mode=\"idle\"}[$__rate_interval]))\n)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Worker CPU Spread (all cores)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\n    (1-irate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"worker\", mode=\"idle\"}[$__rate_interval]))\n)",
     "legendFormat": "max"
    },
    {
     "expr": "quantile(\n    0.8,\n    (1-irate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"worker\", mode=\"idle\"}[$__rate_interval]))\n)",
     "legendFormat": "80pct"
    },
    {
     "expr": "quantile(\n    0.2,\n    (1-irate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"worker\", mode=\"idle\"}[$__rate_interval]))\n)",
     "legendFormat": "20pct"
    },
    {
     "expr": "min(\n    (1-irate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"worker\", mode=\"idle\"}[$__rate_interval]))\n)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(\n    (1-irate(node_cpu_seconds_total{cluster_id=\"$cluster_id\", spec=\"worker\", mode=\"idle\"}[$__rate_interval]))\n)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Worker Memory Spread",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(node_memory_MemTotal_bytes{cluster_id=\"$cluster_id\",spec=\"worker\"} - node_memory_MemAvailable_bytes{cluster_id=\"$cluster_id\",spec=\"worker\"})",
     "legendFormat": "max"
    },
    {
     "expr": "quantile(0.8,node_memory_MemTotal_bytes{cluster_id=\"$cluster_id\",spec=\"worker\"} - node_memory_MemAvailable_bytes{cluster_id=\"$cluster_id\",spec=\"worker\"})",
     "legendFormat": "pct80"
    },
    {
     "expr": "quantile(0.2,node_memory_MemTotal_bytes{cluster_id=\"$cluster_id\",spec=\"worker\"} - node_memory_MemAvailable_bytes{cluster_id=\"$cluster_id\",spec=\"worker\"})",
     "legendFormat": "pct20"
    },
    {
     "expr": "min(node_memory_MemTotal_bytes{cluster_id=\"$cluster_id\",spec=\"worker\"} - node_memory_MemAvailable_bytes{cluster_id=\"$cluster_id\",spec=\"worker\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg(node_memory_MemTotal_bytes{cluster_id=\"$cluster_id\",spec=\"worker\"} - node_memory_MemAvailable_bytes{cluster_id=\"$cluster_id\",spec=\"worker\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Unmanaged Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "min(dask_worker_memory_bytes{cluster_id=\"$cluster_id\",type=\"unmanaged\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg(dask_worker_memory_bytes{cluster_id=\"$cluster_id\",type=\"unmanaged\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "quantile(0.8,(dask_worker_memory_bytes{cluster_id=\"$cluster_id\",type=\"unmanaged\"}))",
     "legendFormat": "80pct"
    },
    {
     "expr": "max(dask_worker_memory_bytes{cluster_id=\"$cluster_id\",type=\"unmanaged\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Managed Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "min(dask_worker_memory_bytes{cluster_id=\"$cluster_id\",type=\"managed\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg(dask_worker_memory_bytes{cluster_id=\"$cluster_id\",type=\"managed\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "quantile(0.8,(dask_worker_memory_bytes{cluster_id=\"$cluster_id\",type=\"managed\"}))",
     "legendFormat": "80pct"
    },
    {
     "expr": "max(dask_worker_memory_bytes{cluster_id=\"$cluster_id\",type=\"managed\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Spilled Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "min(dask_worker_memory_bytes{cluster_id=\"$cluster_id\",type=\"spilled\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg(dask_worker_memory_bytes{cluster_id=\"$cluster_id\",type=\"spilled\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "quantile(0.8,(dask_worker_memory_bytes{cluster_id=\"$cluster_id\",type=\"spilled\"}))",
     "legendFormat": "80pct"
    },
    {
     "expr": "max(dask_worker_memory_bytes{cluster_id=\"$cluster_id\",type=\"spilled\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Managed+Spilled memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "min(sum by(coiled_instance) (dask_worker_memory_bytes{cluster_id=\"$cluster_id\",type!=\"unmanaged\"}))",
     "legendFormat": "min"
    },
    {
     "expr": "avg(sum by(coiled_instance) (dask_worker_memory_bytes{cluster_id=\"$cluster_id\",type!=\"unmanaged\"}))",
     "legendFormat": "avg"
    },
    {
     "expr": "quantile(0.8, (sum by(coiled_instance) (dask_worker_memory_bytes{cluster_id=\"$cluster_id\",type!=\"unmanaged\"})))",
     "legendFormat": "80pct"
    },
    {
     "expr": "max(sum by(coiled_instance) (dask_worker_memory_bytes{cluster_id=\"$cluster_id\",type!=\"unmanaged\"}))",
     "legendFormat": "max"
    }
   ]
  }
 ]
}